Add new health check to service
ONSdigital/dp-search-builder pull request #26
Opened 2020-03-30 15:07 UTC by nshumoogum

### What

Add new health endpoint with the following checkers:

* elasticsearch
* hierarchy api
* kafka consumer
* kafka producer
* kafka error producer (for reporter)

Re-worked entry point to service via main and renamed service package to event and moved graceful shutdown logic to run functionality to be consistent with other applications.

Also includes:
* Use new go dependency manage, modules instead of vendor
* Use latest libraries, dp-kafka, dp-rchttp, dp-api-clients-go, log.go, dp-elasticsearch

### How to review

* Check unit tests pass
* Run an integration test
* Check code changes make sense

### Who can review

Anyone

2020-04-01 08:11 UTC, CarlHembrough requested changes
Good work - just a few minor points to consider

2020-04-01 08:11 UTC, CarlHembrough commented on config/config.go
> +	HealthCheckCriticalTimeout time.Duration `envconfig:"HEALTHCHECK_CRITICAL_TIMEOUT"`
This also needs to be updated in the readme

2020-04-01 08:11 UTC, CarlHembrough commented on event/handler.go
> +			log.Event(ctx, "faile to add children dimension options", log.ERROR, log.Error(err), log.Data{"instance_id": instanceID, "dimension": dimension, "code_id": codeID})
typo "faile"

2020-04-01 08:11 UTC, CarlHembrough commented on go.mod
> +	github.com/ONSdigital/dp-rchttp v0.0.0-20200114090501-463a529590e8
Can this be replaced with a release version?

2020-04-01 08:11 UTC, CarlHembrough commented on main.go
> +			syncConsumerGroup.StopListeningToConsumer(shutdownContext)
Should we be handling the error return value here?

2020-04-01 08:11 UTC, CarlHembrough commented on main.go
> +			searchBuilderErrProducer.Close(shutdownContext)
Should we be handling the error return value here?

2020-04-01 08:11 UTC, CarlHembrough commented on main.go
> +			searchBuiltProducer.Close(shutdownContext)
Should we be handling the error return value here?

2020-04-01 08:11 UTC, CarlHembrough commented on main.go
> +			syncConsumerGroup.Close(shutdownContext)
Should we be handling the error return value here?

2020-04-01 08:11 UTC, CarlHembrough commented on main.go
> +		log.Event(ctx, "error adding check for kafka import producer", log.ERROR, log.Error(err))
"error adding check for kafka search built producer"?

2020-04-01 12:31 UTC, nshumoogum commented on go.mod
> +	github.com/ONSdigital/dp-rchttp v0.0.0-20200114090501-463a529590e8
There is currently no release for this library and James was updating the library with headers - https://github.com/ONSdigital/dp-rchttp/pull/9 - not sure whether we should be creating release 1 or not.

2020-04-01 12:31 UTC, nshumoogum commented on go.mod
> +	github.com/ONSdigital/dp-rchttp v0.0.0-20200114090501-463a529590e8
Actually I will create the first release and update the dependency here

2020-04-02 08:47 UTC, CarlHembrough approved these changes

2020-04-02 08:54 UTC, merged